### ISSUE TITLE
Error for flask db init command

### ISSUE THREAD

**Issue by ns23** [ModoUnreal/nuncio#10]
When I ran `flask db init` command, I  got below error
(env) ➜  nuncio git:(master) flask db init
Usage: flask db init [OPTIONS]

Error: Could not locate Flask application. You did not provide the FLASK_APP environment variable.

For more information see http://flask.pocoo.org/docs/latest/quickstart/`
`

**Python version:3.5.2**
**Flask version :0.12.2**

**Comment by ModoUnreal** [comment]
You first have to run `set FLASK_APP=nuncio.py`. I apologise for not clarifying this in the README file.

**Comment by ModoUnreal** [comment]
I'm going to close this now, since it was just an error in communication.

**Comment by ModoUnreal** [comment]
Ahh of course, the set command is only used on Windows systems!

**Comment by ns23** [comment]
I will update readme file and create PR.. also can you suggest me some good resources to learn flask.

**Comment by ModoUnreal** [comment]
Oh the readme file has already been updated. I'd highly suggest [Miguel Grinberg's Mega Tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) and also the tutorial provided by the framework's developers, [linked here](http://flask.pocoo.org/docs/1.0/tutorial/)

**Comment by ns23** [comment]
Okay thank.. I will go through the resources.
