### ISSUE TITLE
Missing dependancies in requirement.txt

### ISSUE THREAD

**Issue by ns23** [ModoUnreal/nuncio#9]
While doing the setup on my system I got an error saying that 
```
flask_restplus 
flask_bootstrap
```
are missing.

I think those dependencies should be added to requirement.txt

**Comment by ModoUnreal** [comment]
For some reason they refuse to be added to the requirements.txt file, I'll get on this as quickly as possible. Thanks for bringing it up!

**Comment by ModoUnreal** [comment]
I think it's fixed now, could you update your fork and try again?

**Comment by ns23** [comment]
Okay,sure I will update my fork

**Comment by ns23** [comment]
I think this issue is good to close

**Comment by ModoUnreal** [comment]
Cool will do.
